// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team157.robot.subsystems;

import org.usfirst.frc.team157.robot.RobotMap;

import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class MotorSubsystem extends Subsystem
{
    public CANTalon talon;

   
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    @Override
    public void initDefaultCommand()
    {
        System.out.println("MotorSubsystem.initDefaultCommand");
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());\

        try
        {
            talon = new CANTalon(RobotMap.motorSubsystemCANTalonID);
        }
        catch (Exception e)
        {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        
        try
        {
            // jag.setVoltageRampRate(0.02);
            //jag.configNeutralMode(CANJaguar.NeutralMode.Coast);
            //jag.setVoltageMode();
            // jag.setPID(2, 0, 0);
            // jag.enableControl();
            
            //jag.setVoltageRampRate(0.02);
            //jag.configNeutralMode(CANJaguar.NeutralMode.Coast);
            //jag.setVoltageMode();
            //jag.setVoltageMode(CANJaguar.kQuadEncoder, 360 * 3);
            // jag.setPID(2, 0, 0);
            //jag.enableControl();
        }
        catch (Exception e)
        {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    public void setVoltage(double voltage)
    {
        // System.out.println("MotorSubsystem.setVoltage(" + voltage + ")");
        if (null != talon)
        {
            try
            {
                talon.set(voltage);
            }
            catch (Exception e)
            {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
        else
        {
            System.out.println("BUG CHECK: MotorSubsystem.setVoltage -- jag is null");
        }
        
    }

    public void setSpeed(double speed)
    {
        // System.out.println("MotorSubsystem.setSpeed(" + speed + ")");
        if (null != talon)
        {
            try
            {
                talon.set(speed);
            }
            catch (Exception e)
            {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
        else
        {
            System.out.println("BUG CHECK: MotorSubsystem.setSpeed -- jag is null");
        }
    }
}
